export default {
    __schema: {
        types: [
            {
                kind: "INTERFACE",
                name: "_Document",
                possibleTypes: [
                    { name: "Aaaa" },
                    { name: "About_all_contributors" },
                    { name: "About_council" },
                    { name: "About_how_we_help" },
                    { name: "About_how_you_can_help" },
                    { name: "About_main_banner" },
                    { name: "About_management" },
                    { name: "About_office" },
                    { name: "About_strings" },
                    { name: "Author" },
                    { name: "Change_hospitals" },
                    { name: "Company" },
                    { name: "Event" },
                    { name: "Footer" },
                    { name: "Foundation" },
                    { name: "Global_string_pl" },
                    { name: "Header" },
                    { name: "Home_strings" },
                    { name: "Join_club" },
                    { name: "News" },
                    { name: "Partners" },
                    { name: "Payment_approval" },
                    { name: "People" },
                    { name: "Privacy_policy" },
                    { name: "Project" },
                    { name: "ProjectDetailsPage" },
                    { name: "Stopka" },
                    { name: "Support_us" },
                    { name: "Test" },
                    { name: "Test1" },
                    { name: "Write_about_us" },
                    { name: "Wspieraja_nas" },
                ],
            },
            {
                kind: "INTERFACE",
                name: "_Linkable",
                possibleTypes: [
                    { name: "Aaaa" },
                    { name: "About_all_contributors" },
                    { name: "About_council" },
                    { name: "About_how_we_help" },
                    { name: "About_how_you_can_help" },
                    { name: "About_main_banner" },
                    { name: "About_management" },
                    { name: "About_office" },
                    { name: "About_strings" },
                    { name: "Author" },
                    { name: "Change_hospitals" },
                    { name: "Company" },
                    { name: "Event" },
                    { name: "Footer" },
                    { name: "Foundation" },
                    { name: "Global_string_pl" },
                    { name: "Header" },
                    { name: "Home_strings" },
                    { name: "Join_club" },
                    { name: "News" },
                    { name: "Partners" },
                    { name: "Payment_approval" },
                    { name: "People" },
                    { name: "Privacy_policy" },
                    { name: "Project" },
                    { name: "ProjectDetailsPage" },
                    { name: "Stopka" },
                    { name: "Support_us" },
                    { name: "Test" },
                    { name: "Test1" },
                    { name: "Write_about_us" },
                    { name: "Wspieraja_nas" },
                    { name: "_ExternalLink" },
                    { name: "_FileLink" },
                    { name: "_ImageLink" },
                ],
            },
        ],
    },
};
